title: Design Teatime
email: dewberryneun@gmail.com
url: "https://dewberry9.github.io"
github_username: dewberry9
show_excerpts: true
# Build settings
markdown: kramdown
paginate: 7
paginate_path: "list/p:num/"
plugins:
  - jekyll-paginate