title: 환승역 파도
description: "생각과 기록의 모음 - 환승역 파도는 묘한 틈새다. 채움도 다다름도 가만히 지나간다."
email: dewberryneun@gmail.com
author: dewberry9
url: "https://dewberry9.github.io"
show_excerpts: true
# Build settings
markdown: kramdown
pagination:
    enabled: true
    per_page: 9
    limit: 0
    sort_field: "date"
    sort_reverse: true
plugins:
  - jekyll-feed
  - jekyll-paginate-v2