title: Design Teatime
description: "The Page with One Story in a Cup of Tea, Design Teatime."
email: dewberryneun@gmail.com
author: dewberry9
url: "https://dewberry9.github.io"
show_excerpts: true
# Build settings
markdown: kramdown
paginate: 7
paginate_path: "list/p:num/"
plugins:
  - jekyll-paginate